name: Buck build and test
on:
  push:
  pull_request:
jobs:
  linux-buck-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install opam
      - run: opam init --compiler=5.1.1 --disable-sandboxing -y
      - run: eval $(opam env) && ./ocaml-setup.sh
      - run: |
          wget https://github.com/facebook/buck2/releases/download/latest/buck2-x86_64-unknown-linux-gnu.zst
          zstd -d buck2-x86_64-unknown-linux-gnu.zst -o buck2
          chmod +x buck2
          sudo ln -s $(pwd)/buck2 /usr/local/bin/buck2
      - run: cargo install --git https://github.com/facebookincubator/reindeer.git reindeer --force
      - run: reindeer --third-party-dir shim/third-party/rust buckify
      - run: buck2 build shim//third-party/... -v 2
      - run: buck2 build root//... -v 2
  macos-buck-build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: brew install opam
      - run: opam init --compiler=5.1.1 --disable-sandboxing -y
      - run: eval $(opam env) && ./ocaml-setup.sh
      - run: |
          wget https://github.com/facebook/buck2/releases/download/latest/buck2-x86_64-apple-darwin.zst
          zstd -d buck2-x86_64-apple-darwin.zst -o buck2
          chmod +x buck2
          sudo ln -s $(pwd)/buck2 /usr/local/bin/buck2
      - run: cargo install --git https://github.com/facebookincubator/reindeer.git reindeer --force
      - run: reindeer --third-party-dir shim/third-party/rust buckify
      - run: buck2 build shim//third-party/... -v 2
      - run: buck2 build root//... -v 2
