name: Cargo build and test
on:
  push:
  pull_request:
jobs:
  linux-cargo-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install libssl-dev cmake clang lld opam zstd
      - run: opam init --compiler=5.1.1 --disable-sandboxing -y
      - run: eval $(opam env) && ./ocaml-setup.sh
      - run: cargo build
      - run: cargo test
